### ISSUE TITLE
VBoxManage: error: Code NS_BASE_STREAM_WOULD_BLOCK (0x80470007) - Stream operation would block (extended info not available)

### ISSUE THREAD

**Issue by eriksjolund** [eriksjolund/fedora-coreos-vm#5]
When the git commit c7f94ba8e02ec0e71d662de0dd00462e6fe22c13 (git log message "_branch fedora-coreos-experiment4. test 70_") was pushed to Github on Sunday Jul 25 2021 the GitHub Actions workflow _.github/workflows/test.yml_ ran successfully.

Today (5 days later) I clicked "Re-run jobs". This time it failed with

```
VBoxManage: error: Failed to create the VirtualBox object!
VBoxManage: error: Code NS_BASE_STREAM_WOULD_BLOCK (0x80470007) - Stream operation would block (extended info not available)
VBoxManage: error: Most likely, the VirtualBox COM server is not running or failed to start.
(node:1090) UnhandledPromiseRejectionWarning: Error: The process '/usr/local/bin/vboxmanage' failed with exit code 1
    at ExecState._setResult (/Users/runner/work/_actions/eriksjolund/fedora-coreos-vm/fedora-coreos-experiment4/node_modules/@actions/exec/lib/toolrunner.js:592:25)
    at ExecState.CheckComplete (/Users/runner/work/_actions/eriksjolund/fedora-coreos-vm/fedora-coreos-experiment4/node_modules/@actions/exec/lib/toolrunner.js:575:18)
    at ChildProcess.<anonymous> (/Users/runner/work/_actions/eriksjolund/fedora-coreos-vm/fedora-coreos-experiment4/node_modules/@actions/exec/lib/toolrunner.js:469:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:1090) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1090) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

copy-pasted from 

https://github.com/eriksjolund/fedora-coreos-vm/runs/3204420839?check_suite_focus=true

----------

Maybe I have overused some GitHub quota? 
Or maybe this is just a temporary problem on the GitHub side?

**Comment by eriksjolund** [comment]
Sorry, I was confused. I didn't test the source code that I thought I was testing.

```
$ git show c7f94ba8e02ec0e71d662de0dd00462e6fe22c13:.github/workflows/test.yml | grep "uses: er"
      uses: eriksjolund/fedora-coreos-vm@fedora-coreos-experiment4
$ 
```
This configuration will follow the latest commit on the branch _fedora-coreos-experiment4_.
